# Generated by Django 2.1.7 on 2019-03-25 10:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0002_auto_20190325_1118'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_people', models.IntegerField(default=1)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('start_time', models.IntegerField()),
                ('end_time', models.TimeField(default=django.utils.timezone.now)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('walkin', models.BooleanField(default=False)),
                ('reminder', models.BooleanField(blank=True, null=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.Guest')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservations.Table')),
            ],
        ),
    ]
