# Generated by Django 2.1.7 on 2019-02-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reminder',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
