# Generated by Django 2.1.7 on 2019-03-27 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0002_auto_20190327_0829'),
        ('guest', '0002_auto_20190325_1118'),
        ('guest', '0002_auto_20190326_1424'),
    ]

    operations = [
    ]
