# Generated by Django 2.1.7 on 2019-03-27 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0003_merge_20190327_1116'),
        ('guest', '0003_merge_20190327_1054'),
    ]

    operations = [
    ]
